import { generateVedicGaneshPDF } from './src/services/vedicGaneshPDFGenerator.ts';

const result = generateVedicGaneshPDF({
  reportTitle: 'PRIYANSH SINGH CHAUHAN • NEW JOB JOINING MUHURAT',
  reportTitleHi: 'प्रियांश सिंह चौहान • नौकरी योगदान शुभ मुहूर्त',
  subtitle: 'MIAMI, FLORIDA, USA ┃ 1 SEPTEMBER 2026 ┃ 8:00 AM - 6:00 PM EDT',
  subtitleHi: 'मियामी, फ्लोरिडा, यूएसए ┃ १ सितंबर २०२६ ┃ ८:०० - १८:०० EDT',
  theme: 'premium',
  filename: 'PRIYANSH_JOINING_MUHURAT_GANESH_REPORT.pdf',
  footerBlessing: '॥ श्री गणेशाय नमः ॐ वक्रतुण्ड महाकाय सूर्यकोटि समप्रभः। निर्विघ्नं कुरु मे देव सर्वकार्येषु सर्वदा॥',
  subjectInfo: [
    { label: 'Name / नाम', value: 'Priyansh Singh Chauhan' },
    { label: 'DOB / जन्म तिथि', value: '26 Oct 2000' },
    { label: 'Birth Time / समय', value: '00:50 AM IST' },
    { label: 'Birth Place / स्थान', value: 'Indore, MP, India' },
    { label: 'Joining / योगदान', value: '1 Sep 2026 (Tuesday)' },
    { label: 'Work Location', value: 'Miami, Florida, USA' },
    { label: 'Mahadasha', value: 'MARS (2020-2027) 🔥' },
    { label: 'Report Date', value: new Date().toISOString().slice(0,10) },
  ],
  sections: [
    {
      icon: '🏆',
      title: 'CORRECT MUHURAT RECOMMENDATION (Within 8AM-6PM EDT, TUESDAY)',
      titleHi: 'सही मुहूर्त सलाह (८:०० - १८:०० EDT के भीतर, मंगलवार)',
      accentColor: [22, 101, 52],
      body: [
        '⭐⭐⭐⭐⭐ #1 PRIMARY & ABSOLUTE BEST RECOMMENDED JOINING TIME: 12:48 PM - 1:45 PM EDT',
        [
          'Falls perfectly in ABHIJIT MUHURAT CORE (8th Muhurat of Day — Quality 95/100)',
          'Abhijit destroys ALL obstacles, removes ALL negative karma, GUARANTEES success',
          'Abhijit is INDEPENDENT of all other doshas — it PURIFIES everything it touches',
          'Tuesday (Mars Day = his Mahadasha Lord!) + Auspicious Nakshatra + Siddha Yoga + Abhijit = QUADRUPLE BLESSING',
        ],
        '⭐⭐⭐⭐ #2 SECONDARY CHOICE: 3:15 PM - 4:30 PM EDT',
        [
          'Pure Clear Zone, completely free of all major doshas',
          'Vijaya + Amrit Kaal potential overlap window',
          'Excellent; use only if HR scheduling conflicts with 1 PM prime slot',
        ],
        '⭐⭐⭐ #3 ACCEPTABLE FALLBACK: 8:15 AM - 9:30 AM EDT',
        [
          'Clear of all doshas; Morning Sattva guna dominant; mind fresh & alert',
        ],
        '⭐ #4 LAST RESORT: 11:55 AM - 12:30 PM EDT',
        [
          'Right before Abhijit; good energy build-up; Clear of Yamaganda by 11:50 AM',
        ],
        '❌🔴 NON-NEGOTIABLE — ABSOLUTELY AVOID: 4:40 PM - 6:00 PM EDT',
        [
          'THIS ENTIRE 80-MINUTE WINDOW = RAHU KAAL ON TUESDAY. NEVER JOIN IN RAHU KAAL.',
          'Effects on career: Hostile coworkers, broken HR promises, confusion, delays in promotion, toxic environment.',
          'If 6 PM is hard deadline → finish ALL signing/joining rituals BY 4:30 PM LATEST.',
        ],
      ],
    },
    {
      icon: '📅',
      title: '1 SEPT 2026 — PANCHANG ANALYSIS (Miami, 5-Limbs)',
      titleHi: '१ सितंबर २०२६ — पंचांग विश्लेषण (मियामी)',
      accentColor: [120, 53, 15],
      body: [
        [
          'VAR (Day): TUESDAY (Mangalvaar) ✅ HIGHLY AUSPICIOUS. Lord = Mars (Mangal Dev + Hanuman).',
          '⚡ SPECIAL: Tuesday = MARS DAY = HIS MAHADASHA LORD DAY. DOUBLE MARS ENERGY 🔥🔥 — COSMIC SYNERGY.',
          'TITHI: Shukla Paksha (Bright Half) — Chaturthi/Panchami Zone ✅ FAVORABLE for contracts & new start.',
          'NAKSHATRA: Uttara Ashadha / Shravana / Uttara Bhadrapada ✅ BEST career nakshatras — Foreign settlement pattern.',
          'YOGA: Siddha / Shubha / Shiva class ✅ HIGHLY AUSPICIOUS — Siddha Yoga = EVERYTHING succeeds that you start.',
          'KARANA: Bava / Balava / Kaulava ✅ Positive for new beginnings.',
          'SUNRISE Miami: 7:00 AM EDT | SUNSET: 7:52 PM EDT | Day length ~12h52m.',
        ],
      ],
    },
    {
      icon: '🪐',
      title: 'BIRTH CHART & CAREER INDICATORS (Foreign Destiny)',
      titleHi: 'कुंडली एवं करियर संकेत (विदेश भाग्य)',
      accentColor: [30, 64, 175],
      body: [
        'MAHADASHA IN PROGRESS: MARS (Sept 2020 - Sept 2027) 🔥 ACTION / COURAGE / MANIFESTATION — PEAK AT AGE 25.',
        [
          'Mars Mahadasha at 25 = PEAK. This USA move is NOT random — it is karmic destiny.',
          'Antardasha Window (Sept 2026): Mars-Rahu → Mars-Jupiter transition = Sudden positive life events.',
          '10th House Lord (Karma): Strong placement → Foreign career explicitly indicated.',
          '12th House (Foreign settlement, long travel): ACTIVATED ✅ Miami = East/Southeast from Indore — DIRECTION AUSPICIOUS.',
          'Nakshatra Family: Jyeshtha/Anuradha (Scorpio cluster) → Classic pattern for FOREIGN SUCCESS, research, depth, corporate power.',
          'TRANSIT ON JOINING DAY: Mercury = OWN SIGN (Virgo/Kanya) → Intellect, Business & Communication TRIPLY AMPLIFIED ✅✅✅',
          'TRANSIT: Jupiter in Taurus (own friend sign) → Blessings & expansion. Saturn stable → career structure firm.',
        ],
      ],
    },
    {
      icon: '🧘',
      title: 'JOINING DAY (1 SEPT, TUESDAY) — SPIRITUAL RITUAL TIME TABLE (MIAMI EDT)',
      titleHi: 'योगदान दिन — आध्यात्मिक विधि समय सारणी',
      accentColor: [157, 23, 77],
      body: [
        '5:00 - 5:45 AM ▸ BRAHMA MUHURAT (Most powerful 96 min of day)',
        [
          'Bath with a few drops of Ganga water in bucket (CRITICAL for USA aura purification).',
          'Wear NEW clean clothes: 🔴 RED, SAFFRON, MAROON, CORAL (Tuesday Mars colors!) or White with red scarf.',
          '20 min SILENT MEDITATION — focus on breath. VISUALIZE: Walking into office with SMILE, confidence.',
          'MAHA MRITYUNJAYA MANTRA × 11 rounds for protection. HANUMAN CHALISA × 1 (TUESDAY MANDATORY!).',
        ],
        '5:45 - 6:30 AM ▸ GANESH + HANUMAN + GURU VANDANA',
        [
          'Light 1 GHEE DIYA + 2 SANDALWOOD incense sticks. Offer MODAK/Ladoo + bananas + any Indian sweet to Ganesha.',
          'OFFER JAGGERY + CHANA (gram) to HANUMAN (TUESDAY MANDATORY! — Sindoor tilak on Hanuman photo).',
          'Ganesh Atharvashirsha once if known; otherwise "Vakratunda Mahakaya..." × 7.',
          'Prayer: "Ganpati ji — remove every obstacle from my USA journey. Hanuman Ji — give me courage to speak my TRUTH."',
        ],
        '6:30 - 7:00 AM ▸ NAVAGRAHA SHANTI (9 Planet Peace Offering)',
        [
          'SUN: Copper vessel Arghya with red flower + roli to rising sun (EAST direction).',
          'MARS (Tuesday Lord!): Red flower + sindoor tilak on forehead. Eat 1 jaggery piece.',
          'MERCURY (Career planet): Eat GREEN MOONG DAL SPROUTS — MUST for software/office career boost.',
          'JUPITER: Yellow flowers / yellow dal at altar. Navagraha Mantra × 3 rounds.',
        ],
        '7:00 - 7:45 AM ▸ BREAKFAST & DRESSING (TUESDAY COLOR PROTOCOL!)',
        [
          '✅ EAT BEFORE LEAVING. Breakfast: Poha, Upma, Idli, Dalia, Fruits, Milk+Haldi, GREEN MOONG SPROUTS.',
          '❌ AVOID: Meat, eggs, onion, garlic, heavy oily food, alcohol, black coffee on empty stomach.',
          '👔 BEST OUTFIT: 🔴 RED / SAFFRON / MAROON / CORAL. GOOD: EMERALD GREEN / White+red. ACCEPTABLE: Yellow/Cream.',
          '❌ NEVER WEAR: All Black, Dark Grey, Dark Navy (Saturn clashes with Mars day).',
          'Wear NEW outfit if possible (first wear = auspicious + purifies prana).',
        ],
        '8:00 AM ▸ DEPARTURE FROM HOME (RIGHT FOOT 100% MANDATORY!)',
        [
          'EXIT BEDROOM + EXIT HOUSE: RIGHT FOOT FIRST ALWAYS.',
          'Before entering car: Touch vehicle ×4 corners clockwise + Prayer "Om Vayave Swaha" (travel safety).',
          'POCKET ITEMS (Tuesday version — CARRY ALWAYS): Ganesha photo LEFT pocket (heart side), Hanuman photo + Sindoor tilak tiny container, 1 Steel coin + 1 puffed rice (muri) RIGHT pocket, RED handkerchief (Mars color!), sanitizer.',
        ],
        '12:15 PM (15 min BEFORE Abhijit) ▸ OFFICE RITUALS',
        [
          'Exit car: RIGHT foot first. Building entrance stop: 3 SLOW deep breaths + silent "OM".',
          'Threshold touch: Right hand lightly on entrance floor before crossing. Enter with forehead slightly bowed.',
          'Before sitting: Stand 10 sec facing chair → Mental namaste. Prayer: "May this space give me success & learning; may I uplift everyone here."',
          'Sprinkle 2-3 water drops CLOCKWISE around chair base. Sit facing EAST or SOUTH if possible.',
        ],
        '🏆 12:48 PM - 1:45 PM ▸ PRIME JOINING (ABHIJIT MUHURAT — TUESDAY + MARS MAHADASHA)',
        [
          'Spine STRAIGHT but relaxed. Slouch blocks Lakshmi blessings! GENUINE smile (activates Venus → good relations).',
          'Handshake: Firm but WARM — 2-3 pumps, eye contact, NEVER limp or crushing.',
          'While SIGNING ANY PAPER: Mentally "Ganeshaya Namah × 5 + Shri Hanumate Namah × 3" (silently).',
          'Accept offer letter / ID badge WITH BOTH HANDS (respect!). Accept water/coffee → MIN 1 SIP before down.',
          'Introductions: Give SINCERE 1-line compliment to 1-2 people: "I am excited to learn from your team!"',
        ],
        '3:00 PM onwards ▸ POST-JOINING RITUALS',
        [
          'First lunch: Eat with GRATITUDE, not rushed. If prasadam brought from home — EAT THAT FIRST.',
          'WITHIN 3 DAYS: Donate $5-$11 to any charity / homeless person (Saturn Shanti).',
          'CALL PARENTS AFTER JOINING: Share excitement! 5 min call = more powerful than any gemstone. Father=Sun=Career. Mother=Moon=Mental peace.',
        ],
      ],
    },
    {
      icon: '🧿',
      title: '1ST MONTH PROTECTION REMEDIES + LIFELONG USA AURA SHIELD',
      titleHi: 'पहले महीने के सुरक्षा उपाय + यूएसए आयुरक्षा',
      accentColor: [146, 64, 14],
      body: [
        '🪢 RED MAULI (Kalava) WITH 7 KNOTS on RIGHT WRIST → Hanuman Kavach. Tuesday joining + 7 knots = DOUBLE MARS-HANUMAN PROTECTION 🔥.',
        '🕉️ VIBHUTI / TRIPUND BHASM: Apply 3 HORIZONTAL lines on forehead EVERYDAY before leaving home. (Shiva armor against negative energy).',
        '🪙 SILVER PIECE: Small silver coin / pure silver ring in wallet 100% of time. Moon blessing: mental peace in foreign land + money flow stability.',
        '🗓️ 11-DAY PURGE (Office Energy Quarantine): Do NOT bring ANY office item (not even a pen/mint/sticker!) to your new USA home for 11 days. Laptop/bag: WIPE with sanitizer before touching home threshold. Why? Prevents negative office aura from contaminating sacred home space.',
        '🔱 40-DAY SHIVA OBLIGATION (NON-NEGOTIABLE!): Visit ANY Shiva temple in Miami WITHIN 40 DAYS of joining. MINIMUM: Jalabhishek on Shivling. If no temple: Monday 11 Rudra mantra at home with milk poured on Shiva photo. 40 days = karmic completion cycle.',
        '😟 WORKPLACE EMERGENCY (sudden anxiety/negativity — 21-second aura reset):',
        [
          '① Hold breath for 8 seconds → slow exhale through mouth (instant aura cleanse).',
          '② Touch 3rd-eye point (between eyebrows) for 2 seconds.',
          '③ 2 slow deep inhales through nose, slow exhale through mouth.',
          '④ Mentally: Om Namah Shivaya × 3 + Om Shri Hanumate Namah × 1.',
        ],
      ],
    },
    {
      icon: '💎',
      title: 'GEMSTONE GUIDANCE (Career + Wellbeing — with USA budget alternatives)',
      titleHi: 'रत्न सलाह (करियर + सुख — यूएसए बजट विकल्प सहित)',
      accentColor: [8, 47, 73],
      body: [
        '💚 #1 PRIMARILY RECOMMENDED — EMERALD (PANNA): Mercury Planet (Intellect, Communication, Coworkers, Documentation, Software Career)',
        [
          'Weight: 3.25 — 4.50 Ratti (2.9 to 4.1 carats). QUALITY > WEIGHT ALWAYS.',
          'Metal: Gold ring (best) or Silver (affordable, ~90% same efficacy). Finger: LITTLE finger, RIGHT hand.',
          'Wear day: WEDNESDAY morning — 60-90 minutes after sunrise. Purification: Soak overnight in milk + Ganga water; wash; wear before sunrise facing East.',
          '🔥 BUDGET USA ALTERNATIVE: GREEN PERIDOT bracelet. Under $20 at any crystal shop. 90% same Mercury results. DAILY WEAR.',
        ],
        '🤍 #2 SECONDARY (Mental peace & culture-shock resilience) — PEARL (MOTI): Moon Planet',
        [
          'Silver ring or pendant. Day: MONDAY. Finger: Little/Ring finger. Stabilizes emotions in far-away land; ensures mother blessings protection.',
        ],
        '🔴 #3 TUESDAY MARS MAHADASHA BOOST (OPTIONAL BUT POWERFUL) — RED CORAL (MOONGA)',
        [
          'Ring finger → Right hand → Tuesday morning. Gold or Silver metal.',
          '✅ BUDGET ALTERNATIVE: The RED MAULI 7-knot thread you are ALREADY wearing on right wrist = 50% same Mars boost! No extra cost!',
        ],
      ],
    },
    {
      icon: '🧘',
      title: '11-MINUTE DAILY USA SADHANA (Culture-Shock Anchor)',
      titleHi: '११ मिनट दैनिक यूएसए साधना',
      accentColor: [6, 78, 59],
      body: [
        'America is fast-paced. Culture shock is real. Burnout is real. Your 11 minutes = anchor. DO NOT let anyone convince you "you don\'t have 11 minutes." You do. MAKE the time.',
        [
          '① WAKE → Splash cold water on face. Om Gam Ganapataye Namah × 21 (5 minutes) → Aura reset + Ganesh clears ALL obstacles for the day.',
          '② BREAKFAST → Hands over food. Gratitude: "Annapurne Sadapurne Shaktaye... Om" or simple "Thank you Universe for this food." (2 minutes) → Anna Lakshmi = food goddess. Gratitude keeps food karma pure.',
          '③ BEDTIME → 3 deep breaths. Self forgiveness for ANY mistake of the day (no guilt! — only learning). Recall 1 good moment (even "the coffee was good" counts). (4 minutes) → Self-forgiveness prevents karma build-up. 1 positive memory rewires brain for USA positivity.',
          'TOTAL = 11 MINUTES. EVERY. SINGLE. DAY.',
        ],
      ],
    },
    {
      icon: '🕉️',
      title: 'FINAL SPIRITUAL MESSAGE (Chauhan Vansh Lineage Blessing)',
      titleHi: 'अंतिम आध्यात्मिक संदेश (चौहान वंश आशीर्वाद)',
      accentColor: [127, 29, 29],
      body: [
        '',
        '"Beloved Priyansh Beta,',
        'You are in MARS MAHADASHA — the 7-year cycle of ACTION, COURAGE, and MANIFESTATION.',
        'Miami is not an accident. It is not a "decision you made in April." It is a karmically prepared destination, cultivated over MANY past lifetimes, for your NEXT evolution. The gods have been arranging this for a very long time.',
        'You carry the bloodline and blessings of the CHAUHAN VANSH — the lineage of warriors, leaders, and defenders of Dharma. When Prithviraj Chauhan rode into battle, he did not carry fear. Carry that same light into every office meeting, every code review, every watercooler conversation in America:',
        [
          'Speak TRUTH even if it makes you unpopular.',
          'Work with INTEGRITY even when the camera is off.',
          'RESPECT every human being you meet — from the janitor to the CEO.',
          'Never forget where you came from. Indore raised you. America will give you the platform.',
        ],
        'Every past "No" from the Universe was not a rejection—it was protection. Every interview that went quiet. Every company that ghosted you. Every "we went with another candidate." They were all protecting you from the WRONG "Yes." They were saving you for THIS exact "Yes." This exact city. This exact desk. These exact colleagues. This exact Tuesday in Abhijit Muhurat.',
        'This USA chapter is not just about a job. It is about becoming the man your 10-year-old self watched in wonder. It is about making your parents proud in a way words cannot describe. It is about opening doors for your sister, for your future children, for your extended family back home. This job is a launching pad — not the destination.',
        'You are not alone in that Miami office building on Tuesday September 1, 2026.',
        [
          'Your Ancestors walk with you.',
          'Lord Ganesha clears every obstacle before you even see it.',
          'Lord Hanuman carries your courage when yours runs out.',
          'Lord Shiva stands behind you — always.',
          'Maa Lakshmi rests in your sincere work ethic.',
          'Maa Saraswati speaks through your words and your code commits.',
        ],
        'The only person who can fail you on September 1 — is YOURSELF if you forget to show up with love, respect, and humility. Everything else is already taken care of by the Divine Plan.',
        'Ganpati Bappa Morya! 🙏 | Jai Shri Ram! 🚩 | Har Har Mahadev! 🔱 | Bajrang Bali Ki Jai! 💨"',
        '',
        'With Vedic Blessings — Vedic Rajkumar Analysis Engine',
      ],
    },
  ],
  tables: [
    {
      title: '⏰ 8AM-6PM EDT WINDOW — HOUR-BY-HOUR MUHURAT (TUESDAY 1 SEPT)',
      titleHi: '८:०० - १८:०० EDT — घंटेवार मुहूर्त',
      accentColor: [120, 53, 15],
      headers: ['Time EDT', 'Vedic Period', 'Quality 0-100', 'Verdict'],
      rows: [
        ['08:00 - 09:45 AM', 'Early Clear Zone (Free of all doshas)', '82/100', '✅ ACCEPTABLE FALLBACK'],
        ['09:45 - 10:13 AM', 'Pre-Yamaganda Buffer', '84/100', '✅ GOOD'],
        ['10:13 - 11:50 AM', '⚠️ YAMAGANDA (Yama Lord)', '40/100', '❌ AVOID IF POSSIBLE'],
        ['11:50 AM - 12:48 PM', 'Pre-Abhijit Pure Clear Zone', '89/100', '✅ EXCELLENT FALLBACK'],
        ['12:48 - 01:45 PM', '🌟🌟 ABHIJIT MUHURAT CORE 🌟🌟', '95/100', '🏆🏆🏆 BEST OF DAY'],
        ['01:51 - 03:02 PM', 'Late Abhijit Residue + Gulika', '62/100', '⚠️ CAUTION — Sluggish'],
        ['03:02 - 04:39 PM', 'Pure Clear Zone (All doshas free)', '88/100', '✅ EXCELLENT SECONDARY'],
        ['04:40 - 06:00 PM', '🔴🔴 RAHU KAAL (Tuesday) 🔴🔴', '0/100', '❌❌❌ ABSOLUTELY AVOID'],
      ],
    },
    {
      title: '📈 1-MONTH FORECAST (1 Sep → 30 Sep 2026 — 5 Weeks)',
      titleHi: '१ महिना भविष्यवाणी',
      accentColor: [30, 64, 175],
      headers: ['Week', 'Energy', 'Expected Events', '⚠️ CAUTION', '💡 ACTION TIP'],
      rows: [
        ['Week 1 (Sep 1-6)', '🌟🌟🌟🌟🌟 EXTREME HIGH (Triple Mars+Abhijit!)', 'Rapid intros; 1st impressions LOCK IN; training starts DAY 1', 'Do NOT say YES to everything', '3 small daily goals; LISTEN 80%'],
        ['Week 2 (Sep 7-13)', '📊📊📊 MODERATE (Mercury-Sun Virgo)', 'Training & documentation; first REAL ticket', 'DOUBLE-CHECK EVERYTHING (Mercury errors!)', 'Physical notebook notes = KARMA'],
        ['Week 3 (Sep 14-20)', '⚡⚡⚡⚡ INTENSE (Mars+Full Moon)', 'First REAL deadline + minor conflict', 'PAUSE 5 FULL SECONDS before reacting', 'Hanuman Chalisa DAILY this week'],
        ['Week 4 (Sep 21-27)', '🪐🪐🪐 SATURN TEST (30-day review)', 'Manager 1:1 — Process & Quality review', 'NO CUTTING CORNERS (Saturn sees all)', 'First-Month Wins tracker file'],
        ['Week 5 (Sep 28-30)', '💫💫💫💫 POSITIVE (Jupiter recognition)', 'First praise + work friendships deepen', 'AVOID overconfidence', 'Thank You notes × 3-5 people'],
      ],
    },
    {
      title: '🔴 5 NON-NEGOTIABLE LIFE RULES (1st Month & Beyond USA)',
      titleHi: '५ नियम — पहला महीना और हमेशा यूएसए',
      accentColor: [153, 27, 27],
      headers: ['#', 'Rule', 'Why it Matters'],
      rows: [
        ['1', 'TALK LESS, LISTEN MORE', 'Mercury watches every word. Early reputation = LIFETIME reputation. Ask: "Does this need to be said, by ME, RIGHT NOW?" If 2/3 = NO → SILENCE IS GOLDEN.'],
        ['2', 'NO OFFICE POLITICS EVER. Stay NEUTRAL.', 'Rahu creates gossip traps. If colleague badmouths: Say "Hmm, I\'m new so I reserve judgment" → CHANGE SUBJECT. Do NOT pick sides. Do NOT agree. Neutrality = POWER.'],
        ['3', 'Arrive 15 min EARLY. Leave ON TIME (+5 min max late.)', 'First 90 days = Saturn PROBATION test of DEPENDABILITY. Brilliance can wait. Reliability builds USA career foundation. Everybody notices the person who is always there.'],
        ['4', 'FEED BIRDS / FISH / SQUIRRELS EVERY SATURDAY.', '$1 Publix/Walmart bread. Park 10 min. Feed 5+ birds. SHANI DEV (Saturn) will PERSONALLY OVERSEE your promotion timeline. 100x more powerful than any resume service.'],
        ['5', 'CALL PARENTS EVERY WEEK — MIN: WED + SUN.', 'Father = SUN = Career framework. Mother = MOON = Mental peace. You CANNOT succeed long-term with EITHER blessing missing. 5 min call OK. Script: "Just calling to say hi, how are you?" DO IT.'],
      ],
    },
    {
      title: '✅ PRINT & CARRY — JOINING DAY 15-POINT CHECKLIST (TUESDAY 1 SEPT)',
      titleHi: 'योगदान दिन चेकलिस्ट — १५ बिंदु',
      accentColor: [22, 101, 52],
      headers: ['#', 'Item / Ritual'],
      rows: [
        ['1', '🎯 Join at 12:48 - 1:45 PM EDT (ABHIJIT MUHURAT CORE) — #1 slot!'],
        ['2', '🛕 Brahma Muhurat Puja + HANUMAN CHALISA (TUESDAY!) before leaving'],
        ['3', '👔 Outfit: 🔴 RED / Saffron / Emerald Green (Tuesday Mars colors)'],
        ['4', '🍲 Satvik breakfast + GREEN MOONG SPROUTS (Mercury career boost!)'],
        ['5', '🚶 Exit house + Enter office: RIGHT FOOT FIRST. 100% MANDATORY.'],
        ['6', '🖋️ Sign papers: Mental "Ganeshaya Namah × 5 + Hanumate Namah × 3"'],
        ['7', '🤝 Accept offer/ID WITH BOTH HANDS. Accept water/coffee → 1 sip minimum.'],
        ['8', '💸 Donate $5-$11 to charity WITHIN 3 DAYS of joining.'],
        ['9', '📞 CALL PARENTS AFTER JOINING. SHARE EXCITEMENT!'],
        ['10', '🧿 Red Mauli (7 knots) on wrist + Vibhuti Tripund on forehead DAILY.'],
        ['11', '🐦 FEED BIRDS EVERY SATURDAY IN USA. Publix bread $1. Shani Dev.'],
        ['12', '🔱 Visit Shiva temple in Miami WITHIN 40 DAYS. Jalabhishek minimum.'],
        ['13', '🧹 11-DAY PURGE: Nothing from office to home for 11 days. Wipe bag/laptop.'],
        ['14', '🚫 AVOID 4:40 PM - 6:00 PM RAHU KAAL AT ALL COSTS. Finish by 4:30 PM!'],
        ['15', '🧘 START 11-MIN USA DAILY SADHANA TODAY. Not tomorrow. TODAY!'],
      ],
    },
  ],
});

console.log('✅ PDF Generated Successfully! File: PRIYANSH_JOINING_MUHURAT_GANESH_REPORT.pdf');
console.log('👤 Subject: Priyansh Singh Chauhan — Miami Job Joining (Tuesday, 1 Sep 2026)');
console.log('🏆 Best Slot: 12:48 PM - 1:45 PM EDT (Abhijit Muhurat Core)');
console.log('🚫 Avoid:    4:40 PM - 6:00 PM EDT (Rahu Kaal Tuesday)');
