const fs = require('fs');
const c = fs.readFileSync('src/pages/Index.tsx', 'utf8');
const idx = c.indexOf('"Mundane"}');
const start = c.lastIndexOf('{isHi', idx);
const chunk = c.substring(start, idx + 10);
const qi = chunk.indexOf('"');
const qi2 = chunk.indexOf('"', qi + 1);
const g = chunk.substring(qi + 1, qi2);
const bytes = Buffer.from(g, 'utf8');
const fixed = Buffer.from(bytes.toString('latin1'), 'latin1').toString('utf8');
console.log('FIXED:' + fixed);
