/**
 * ============================================================
 * PRASHNA (HORARY ASTROLOGY) — Domain Type Contracts
 * ============================================================
 *
 * Prashna ("question") is the Vedic horary system: a chart is cast
 * for the exact moment a question is sincerely asked, and the chart
 * is analysed to answer that question without requiring the querent's
 * birth data.
 *
 * CALCULATION CONTRACT:
 *   Input  : PrashnaQuery  (question + moment + location)
 *   Engine : Cast chart for `askedAt` moment at (latitude, longitude).
 *            Identify the question's significators (Lagna, 7th house,
 *            Moon, lord of relevant house for the topic).
 *            Apply Vedic Prashna rules (Nashta Jataka, Tajika aspects,
 *            dignity, transit, Ashtamangala).
 *   Output : PrashnaAnswer  (verdict + reasoning + significators + remedies)
 *
 * TOPIC CLASSIFICATION:
 *   The `topic` field maps to a house signification:
 *     marriage/relationship → 7th house
 *     career/job            → 10th house
 *     health                → 1st / 6th house
 *     finance/money         → 2nd / 11th house
 *     property/home         → 4th house
 *     travel                → 3rd / 9th / 12th house
 *     litigation/dispute    → 6th / 7th house
 *     general               → 1st house (Lagna)
 *
 * AI INTEGRATION NOTE:
 *   The `reasoning` field is Markdown and may be generated by an LLM
 *   conditioned on the chart data + Prashna rules. The `significators`
 *   field must always be grounded in the actual chart — not hallucinated.
 *   See PrashnaAnswer.isAIGenerated for provenance tracking.
 *
 * HISTORY:
 *   PrashnaSessions are persisted in Supabase (Week 5) under the
 *   `prashna_sessions` table, keyed by `query.id`.
 * ============================================================
 */

import type { BirthData, Planet, Sign, ChartResult } from '@/features/kundli/types';

// ─── Question input ───────────────────────────────────────────────────────────

/**
 * Broad topic categories that determine which house is examined as the
 * primary significator house for the question.
 */
export type PrashnaTopicCategory =
  | 'marriage'
  | 'relationship'
  | 'career'
  | 'finance'
  | 'health'
  | 'property'
  | 'travel'
  | 'education'
  | 'litigation'
  | 'spirituality'
  | 'general';

/**
 * The querent's question as submitted through the UI.
 *
 * The engine uses `askedAt` + `latitude` + `longitude` to cast the
 * Prashna chart. `question` is used by the AI layer for contextual
 * interpretation. `birthData` is optional — when provided it enables
 * Natal + Prashna combined analysis.
 */
export interface PrashnaQuery {
  /**
   * Unique identifier for this query (UUID v4).
   * Generated client-side before submission so optimistic UI is possible.
   */
  id: string;

  /** The question text as entered by the user. Max 500 characters. */
  question: string;

  /**
   * ISO 8601 UTC timestamp of when the question was sincerely raised.
   * The Prashna chart is cast for this exact moment.
   * If the user delays submitting, the timestamp should reflect when
   * the question first arose in the mind, not when the form was submitted.
   */
  askedAt: string;

  /** Geographic latitude of the querent at the time of asking. Decimal degrees, N positive. */
  latitude: number;

  /** Geographic longitude of the querent at the time of asking. Decimal degrees, E positive. */
  longitude: number;

  /** IANA timezone at the location of asking. */
  timezone: string;

  /** Best-fit topic category — helps the engine focus on the right house. */
  topic: PrashnaTopicCategory;

  /**
   * Optional natal chart of the querent.
   * When present, the engine compares Prashna chart with natal for
   * Dasha-transit correlation and stronger significator analysis.
   */
  natalData?: BirthData;
}

// ─── Answer output ────────────────────────────────────────────────────────────

/**
 * The primary verdict — intentionally simple for clear communication.
 * 'unclear' means the chart has mixed or contradictory indications.
 */
export type PrashnaVerdict = 'yes' | 'no' | 'maybe' | 'unclear';

/**
 * A single astrological significator cited in the analysis.
 * Both the planet/point and its role in the reasoning must be named.
 */
export interface PrashnaSignificator {
  /** The planet or sensitive point. */
  planet: Planet;

  /** The sign the planet occupies in the Prashna chart. */
  sign: Sign;

  /** The house the planet occupies in the Prashna chart (1–12). */
  house: number;

  /**
   * One-sentence explanation of why this planet is a significator
   * for this specific question. Must be grounded in the chart.
   * Example: "Moon as Lagna lord aspects the 7th house significator Venus."
   */
  role: string;

  /** Whether the planet's dignity supports (true) or opposes (false) the verdict. */
  supportive: boolean;
}

/**
 * Timing indication when the Prashna suggests a YES outcome.
 * Expressed as a range because Prashna timing is approximate.
 */
export interface PrashnaTiming {
  /** Earliest likely date (ISO YYYY-MM-DD). */
  earliest: string;

  /** Latest likely date (ISO YYYY-MM-DD). */
  latest: string;

  /**
   * Human-readable timing description.
   * Example: "Within 3–6 months (Mercury sub-period of Venus Dasha)"
   */
  description: string;
}

/**
 * One suggested remedy from the Prashna analysis.
 * Remedies must be proportionate and grounded — no superstitious exaggeration.
 */
export interface PrashnaRemedy {
  /** Type of remedy. */
  type: 'mantra' | 'fast' | 'charity' | 'gemstone' | 'puja' | 'colour' | 'general';

  /** Plain-language instruction. */
  instruction: string;

  /** Planet or dosha this remedy targets. */
  targetPlanet?: Planet;

  /** Number of days/repetitions if applicable. */
  duration?: string;
}

/**
 * The engine's complete answer to a Prashna query.
 *
 * Immutability guarantee: once an answer is persisted (Supabase),
 * the `verdict` and `significators` must not be mutated — append a
 * new PrashnaAnswer with a new `queryId` if re-analysis is needed.
 */
export interface PrashnaAnswer {
  /** Matches `PrashnaQuery.id`. */
  queryId: string;

  /** The Prashna chart cast at the moment of asking. */
  prashnaChart: ChartResult;

  /** The primary yes/no/maybe verdict. */
  verdict: PrashnaVerdict;

  /**
   * Confidence in the verdict as a fraction [0, 1].
   * > 0.8 = clear indication; 0.5–0.8 = moderate; < 0.5 = unclear.
   * The engine should not return 'yes' or 'no' with confidence < 0.5.
   */
  confidence: number;

  /**
   * The astrological reasoning in Markdown.
   * Must include: Lagna sign/lord, significator planets, key aspects,
   * and the logical chain leading to the verdict.
   * Max length: 2000 characters. Use concise, non-sensationalist language.
   */
  reasoning: string;

  /** Planets and points that drove the verdict — minimum 2, maximum 6. */
  significators: PrashnaSignificator[];

  /**
   * Timing window for the outcome (only present when verdict = 'yes').
   * Omit for 'no', 'maybe', or 'unclear' verdicts.
   */
  timing?: PrashnaTiming;

  /** Suggested remedies if there are obstacles or the verdict is borderline. */
  remedies: PrashnaRemedy[];

  /**
   * True if the `reasoning` text was generated or augmented by an LLM.
   * False if it was produced purely by rule-based engine logic.
   * UI should display appropriate disclosure when true.
   */
  isAIGenerated: boolean;

  /** ISO 8601 UTC timestamp when this answer was produced. */
  answeredAt: string;

  /** Semver of the Prashna engine that produced this answer, for reproducibility. */
  engineVersion: string;
}

// ─── Session (query + answer together) ───────────────────────────────────────

/**
 * A complete Prashna session as stored in the database.
 * `answer` is undefined while the engine is processing.
 */
export interface PrashnaSession {
  query: PrashnaQuery;
  answer?: PrashnaAnswer;

  /**
   * User ID (Clerk) who owns this session.
   * null = anonymous (limited retention: 24 hours).
   */
  userId: string | null;

  /** ISO timestamp when the session was created. */
  createdAt: string;

  /** ISO timestamp of last update (e.g. when answer was attached). */
  updatedAt: string;
}

// ─── History ──────────────────────────────────────────────────────────────────

/** Summary record shown in the Prashna history list. */
export interface PrashnaHistoryItem {
  sessionId: string;
  question: string;
  topic: PrashnaTopicCategory;
  verdict?: PrashnaVerdict;
  askedAt: string;
  hasAnswer: boolean;
}
